### ISSUE TITLE
We need you help with Plex (PMS)

### ISSUE THREAD

**Issue by anvme** [sergiou87/sergiou87.github.io#1]
¡Hola! Please, help us with the old bug 
Thank u for updates, but, please, fix the problem from 2014y, yes, 2014 year. 
We have a topic at this forum and on Reddit too. This is no hard, and on Reddit, u can find the solution.
So, topic on plex forum - [Discussion](https://forums.plex.tv/t/search-is-case-sensitive-with-cyrillic-characters/141491/28), [BUG](https://forums.plex.tv/t/bug-search-should-be-case-and-diacritics-insensitive/87638) with 56 votes.
And Reddit with the solution at StackOverflow [here](https://www.reddit.com/r/PleX/comments/f7czff/search_should_be_case_and_diacritics_insensitive/)

**Comment by sergiou87** [comment]
Hey! Sorry I have to close this issue, this is not the best place to tackle that problem 😅 

However, I've passed the message to the server team. Please, write me a DM in the forums for more info!
